version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:v1.8.4
    container_name: evolution-api
    restart: unless-stopped
    ports:
      - "8084:8080"
    environment:
      AUTHENTICATION_API_KEY: "JASS_EVOLUTION_KEY_2024"
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: "true"

      SERVER_URL: "http://localhost:8084"
      SERVER_TYPE: "http"

      LOG_LEVEL: "ERROR,WARN,INFO,LOG"
      DEL_INSTANCE: "false"

      DATABASE_ENABLED: "false"

      STORE_MESSAGES: "true"
      STORE_MESSAGE_UP: "true"
      STORE_CONTACTS: "true"
      STORE_CHATS: "true"

      WEBHOOK_GLOBAL_ENABLED: "false"

      QRCODE_LIMIT: 30
      QRCODE_COLOR: "#198754"

    volumes:
      - evolution_data:/evolution/instances
      - evolution_store:/evolution/store

volumes:
  evolution_data:
  evolution_store:
