spring:
     r2dbc:
          url: ${DATABASE_URL}
          username: ${DATABASE_USER}
          password: ${DATABASE_PASSWORD}
          pool:
               initial-size: 3
               max-size: 10

     flyway:
          enabled: true
          url: ${DATABASE_JDBC_URL}
          user: ${DATABASE_USER}
          password: ${DATABASE_PASSWORD}
          table: flyway_schema_history_inventory

     rabbitmq:
          host: ${RABBITMQ_HOST}
          port: ${RABBITMQ_PORT:5672}
          username: ${RABBITMQ_USER}
          password: ${RABBITMQ_PASSWORD}
          ssl:
               enabled: ${RABBITMQ_SSL_ENABLED:false}

springdoc:
     api-docs:
          enabled: false
     swagger-ui:
          enabled: false

logging:
     level:
          root: WARN
          pe.edu.vallegrande: INFO
