spring:
     data:
          mongodb:
               uri: ${MONGODB_URI:mongodb+srv://sistemajass:ZC7O1Ok40SwkfEje@sistemajass.jn6cpoz.mongodb.net/JASS_DIGITAL?retryWrites=true&w=majority&maxPoolSize=10&minPoolSize=2&maxIdleTimeMS=30000&serverSelectionTimeoutMS=3000&heartbeatFrequencyMS=30000}

     rabbitmq:
          host: ${RABBITMQ_HOST:localhost}
          port: ${RABBITMQ_PORT:5672}
          username: ${RABBITMQ_USER:guest}
          password: ${RABBITMQ_PASSWORD:guest}

app:
     evolution-api:
          base-url: http://localhost:8084
          api-key: JASS_EVOLUTION_KEY_2024
          instance-name: jass-whatsapp
     organizations-api:
          base-url: http://localhost:8083

logging:
     level:
          pe.edu.vallegrande: DEBUG
          org.springframework.amqp: DEBUG

resilience4j:
     circuitbreaker:
          instances:
               organizationsApi:
                    sliding-window-size: 10
                    failure-rate-threshold: 50
                    wait-duration-in-open-state: 10s
                    permitted-number-of-calls-in-half-open-state: 5
                    register-health-indicator: true
