spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_jass_organizations
      auto-index-creation: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    pe.edu.vallegrande.vgmsorganizations: DEBUG
    org.springframework.data.mongodb: DEBUG

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:drqpwb5rq}
  api-key: ${CLOUDINARY_API_KEY:376462778114431}
  api-secret: ${CLOUDINARY_API_SECRET:47C9YZgGsnXTCEu-yrifnY8NC5E}